### ISSUE TITLE
Bluetooth is not working

### ISSUE THREAD

**Issue by yukigod17** [VinylNerd/ThinkPad-T440P-OpenCore#1]
Bluetooth is not working

**Comment by VinylNerd** [comment]
could you let me know which wifi card you are using? i will consider making a seperate build for other cards if there is enough demand, currently this build is designed to work only with Apple WiFi cards on T440P with modded BIOS to allow for any card.

cards tested and working on this build which i recomend are

BCM94360CS or BCM94360CS2, they can be tricky to fit but i give some explanation in the readme
