### ISSUE TITLE
BCM94360CS2 Install Problem

### ISSUE THREAD

**Issue by ProjectAI360** [VinylNerd/ThinkPad-T440P-OpenCore#11]
Could you describe how you installed your BCM94360CS2 card? Do you have to remove the ethernet card to make it fit? I removed it and it's still not able to sit flush due to the ethernet connector on the motherboard protruding. And when I put the cover back on the BCM94360CS2 is too long, so did you cut out the plastic to make it fit?

This is the converter I'm using:
https://www.amazon.com/gp/product/B085HBBB6B/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1

**Comment by ProjectAI360** [comment]
Nevermind, I just used a dremel to cut out the plastic to make it fit and removed the ethernet card. Suppose I'll just use  a usb adapter if I ever need ethernet. The BCM94360CS2 works great!!

**Comment by VinylNerd** [comment]
hey @EvilistMonkey you actually dont need to remove the ethernet adapter, as the wifi card can actually fit at an angle and sit ontop of it, the bottom of the case has to be shaved out a little bit to allow it to fit properly after that, but personally i have the same card and ethernet :)

**Comment by ProjectAI360** [comment]
Ahh ok, I'll give that a shot. I wasn't sure if I could have it at an angle like that. So are you just using some adhesive to make it stick to the ethernet card?

**Comment by VinylNerd** [comment]
i just sit it there ontop of the ethernet card, you could use some adhesive but it will also make the fit tighter, i had to shave out the inside of my case in order to make it fit properly, sorry for the delay in response
