### ISSUE TITLE
CPU compatability 

### ISSUE THREAD

**Issue by BigButcherBoy** [VinylNerd/ThinkPad-T440P-OpenCore#12]
Hi
I have a engineering sample of the CPU I7 4702MQ and cannot get it to boot past the apple logo. I have the original CPU for my T440P and that works fine but is pretty underpowered. I was wondering if there was any setting to change in the configuration to help identify the CPU properly? 

This might be more suitable for the Opencore github page so sorry if I am in the wrong place, I am just using your configuration and any help would be useful, thank you!

**Comment by VinylNerd** [comment]
sorry i am not sure about why this would be, i also ordered a 4702MQ that didnt work but it wasnt an ES and i couldnt even get into bios, turned out chip was bad, now running 4710MQ and its great

**Comment by BigButcherBoy** [comment]
Ah I see that's a shame, I also have a beefier I7 4810MQ that does work but obviously more heat and less battery life isn't ideal but it's a step up from the stock dual core. I'll stick with that for now but thanks anyway.

**Comment by VinylNerd** [comment]
issue closed
