### ISSUE TITLE
Graphical glitches with sidecar

### ISSUE THREAD

**Issue by Alfoten7839** [VinylNerd/ThinkPad-T440P-OpenCore#14]
Hello,

Thanks to your project I was able to put MacOS Big Sur on my T440p. Everything works perfectly but when I use Sidecar on my iPad mini 5 ipadOS 15.2 (in bluetooth as by cable) I have graphic glitches.

I use macOS 11.6.2 and your release v0.6-beta1 with an i7 4800MQ processor. I read on a forum that it could be a problem because Sidecar encodes in HEVC (H.265) and that 4th generation processors don't handle it well... Is it indeed a hardware problem or is there a way to fix it ?

Thanks in advance.

**Comment by VinylNerd** [comment]
do you have the FeatureUnlock.kext enabled? i dont have an iPad so i can't test this unfortunately :( sorry

**Comment by Alfoten7839** [comment]
Yes I did activate the feature but I really think it's a processor problem because the real Macs from those years (not Sidecar compatible) if they activate it have the same problem.

**Comment by VinylNerd** [comment]
have you had any progress on resolving the glitches?

**Comment by Alfoten7839** [comment]
The problem is still present but it's a hardware problem (CPU architecture is too old), we will not be able to correct the problem.

In any case, thank you for your work =)
