### ISSUE TITLE
Problem with Mini DisplayPort connector

### ISSUE THREAD

**Issue by EdsonLuiz** [VinylNerd/ThinkPad-T440P-OpenCore#15]
- There are cuts in the transmission of image and sound. 
- Tested on all resolutions and refresh rates(max 60 hertz).
- Problem occurs with notebook screen open or closed
- Discarded problem with the cable, as it works normally on windows and linux.
- Also error occurs in preferences when MdisplayPort is connected.
- Bios setup allocates 512mb for video.

Thank you, I am available for more information if necessary.

![dport01](https://user-images.githubusercontent.com/5461553/147877076-d3dc5c3e-6892-4ffc-a95b-9012040e1a9b.png)

![dport02](https://user-images.githubusercontent.com/5461553/147877090-f193a130-9eb9-4385-a8d0-0a6a310455f2.png)

**Comment by VinylNerd** [comment]
i am not sure, for my screen i use MiniDP to HDMI to 1080p 75Hz Monitor and i have no issues except for slow connection when i plug in sometimes

**Comment by EdsonLuiz** [comment]
Update:
- With MiniDP to Display port cable works above 1080p, but with cuts in image transmission and errors in the preference panel. 
- With MiniDP to HDMI converter works up 1080p with random white pixels appearing in many parts of the screen. 
- To solve the problem I used another EFI (valnoxy/t440p-oc) along with MiniDP to HDMI converter.

I will close this issue, as I consider it resolved. @VinylNerd Thanks for the HDMI tip.
