### ISSUE TITLE
HDMI & Wifi not working

### ISSUE THREAD

**Issue by mortuzahossain** [VinylNerd/ThinkPad-T440P-OpenCore#2]
Hi,
Hope you are doing great. I am using your EFI configuration v0.3-beta2 but it is not working some features one of them is HTMI. The others are Wifi. Even when I use Mojave it did not work so I use to use wn725n tp link usb wifi adapter. But it is not installing. Your help is highly appreciated. Thank you so much you put together this much effort for this community. 

Thank you

**Comment by mortuzahossain** [comment]
I wants to use duel display and my secondary display is a LG 20MP48A - P

**Comment by VinylNerd** [comment]
Hello, which WI-FI card are you using? the stock intel card?

- please use v0.4-beta1 and report if still having same issues

**Comment by mortuzahossain** [comment]
Using v0.4-beta1 fixed the problem.

But initially, the audio disabled. Then I download VoodooHDA and working fine.

Thank you.

**Comment by VinylNerd** [comment]
beautiful. issue closed, thank you for your feedback.
