### ISSUE TITLE
Forget to Generating own serial 

### ISSUE THREAD

**Issue by mortuzahossain** [VinylNerd/ThinkPad-T440P-OpenCore#4]
Unfortunately, I forgot to generate my own serial number. My setup is working fine. Is it necessary to add it. Please clear why this is needed. If so how may I add this now? I am new to this Hackintosh setup.

**Comment by mortuzahossain** [comment]
![Screenshot 2021-06-10 at 1 58 50 AM](https://user-images.githubusercontent.com/14279461/121421491-07e73a80-c990-11eb-927f-4a4345b575b2.png)

**Comment by HackiMaci** [comment]
Hi mortuzahossain,

follow the Steps and than you have all Serials


You need a script, called GenSMBIOS, to create fake serial number, UUID and MLB numbers. This step is essential to have working iMessage, so do not skip it!

The process is the following:

Download GenSMBIOS as a ZIP, then extract it.
Start GenSMBIOS.bat and use option 1 to download MacSerial.
Choose option 2, to select the path of the config.plist file. It will be located in EFI -> OC folder.
Choose option 3, and enter MacBookPro11,1 as the machine type.
Press Q to quit. Your config now should contain the requied serials.

Ps. Also add in PlatformInfo -> Generic -> ROM you proper MAC address.


Regards

HackiMaci

**Comment by VinylNerd** [comment]
what @HackiMaci has said is correct.

i will add that you can use an unvalid serial, or a serial which has Purchase Date not Validated

i dont recomend using a valid serial as it can use to problems with your apple ID 

you can use this page to check status of the serial generated using SMBIOS

https://checkcoverage.apple.com/gb/en/

i will close the issue in 7 days if no response is made.
