### ISSUE TITLE
Disabling SIP v0.4-beta1

### ISSUE THREAD

**Issue by widiu7omo** [VinylNerd/ThinkPad-T440P-OpenCore#5]
Hello Vin, could you give advise, which method should I use to disabling SIP? according to this link [https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/extended/post-issues.html#disabling-sip](url), there are some methods. Should I disable entire flags? or just kext signing (0x1) and filesystem protections. Thanks

**Comment by VinylNerd** [comment]
either will work, but only kext signing and filesystem protection is needed to be disabled.
