### ISSUE TITLE
Boot Loop after 1st Installer Reboot

### ISSUE THREAD

**Issue by AwlsomeAlex** [VinylNerd/ThinkPad-T440P-OpenCore#7]
Hello,
I tried using the latest release (v0.4-beta1) with macOS 11.2.3 and 11.4. 
I am able to boot into the macOS Installer and initialize the install, but after the first reboot my laptop goes into a boot loop.
The boot menu will appear once and I'll select "macOS Installer", but after that it panics and goes into a boot loop, where the OC menu won't even appear.
I also had some issues in 11.4 where it would mess with my EFI bootloader, with the BIOS having to recover some EFI variables.
I can supply more information as requested. Thanks!
The only thing non-baseline about my T440p is that it has an FHD IPS screen mod.

**Comment by Thevirtualmask** [comment]
during installation, did you format the hdd in APFS?

**Comment by AwlsomeAlex** [comment]
> during installation, did you format the hdd in APFS?

No the HDD was formatted HFS+

**Comment by VinylNerd** [comment]
i am not sure if AFPS must be used, but i would assume you need to use an AFPS formatted drive.

**Comment by Thevirtualmask** [comment]
you need to format in APFS for it to work

**Comment by AwlsomeAlex** [comment]
Oh must be different from Clover/Catalina. That worked thanks.
