### ISSUE TITLE
speaker not working

### ISSUE THREAD

**Issue by karnadii** [VinylNerd/ThinkPad-T440P-OpenCore#8]
Hey, thanks for your work. Just updated to macos big sur with your EFI. My only problem is the audio did not work for me. any idea what was wrong? previously I use sniki EFI in catalina. with bluetooth speaker I have no problem, but the internal speaker and docking audio jack not working

**Comment by VinylNerd** [comment]
https://github.com/VinylNerd/ThinkPad-T440P-OpenCore/releases/tag/v0.4-beta1

please follow instructions outlined here, let me know if any issues, please close if you solve it

**Comment by karnadii** [comment]
I can't make voodoohda work, using apple alc can not get rid the noise when jack is connected. nevermind, I'll just use bluetooth speaker
