### ISSUE TITLE
BCM943224PCIEBT2 issues solved

### ISSUE THREAD

**Issue by purpose-pending** [VinylNerd/ThinkPad-T440P-OpenCore#9]
For people, who used [Wolfgang's guide](https://github.com/notthebee/t440p-airport) to fit BCM943224PCIEBT2 inside - WiFi doesn't work with this EFI (at least it didn't work for me).   
Solved by adding AirportBrcmFixup.kext from [this repo](https://github.com/lighterEB/ThinkPad-T440p/tree/main/EFI-OC/OC/Kexts) and importing it in the config.plist : 

```
			<dict>
				<key>Arch</key>
				<string>Any</string>
				<key>BundlePath</key>
				<string>AirportBrcmFixup.kext</string>
				<key>Comment</key>
				<string></string>
				<key>Enabled</key>
				<true/>
				<key>ExecutablePath</key>
				<string>Contents/MacOS/AirportBrcmFixup</string>
				<key>MaxKernel</key>
				<string></string>
				<key>MinKernel</key>
				<string></string>
				<key>PlistPath</key>
				<string>Contents/Info.plist</string>
			</dict>
			<dict>
				<key>Arch</key>
				<string>Any</string>
				<key>BundlePath</key>
				<string>AirportBrcmFixup.kext/Contents/PlugIns/AirPortBrcmNIC_Injector.kext</string>
				<key>Comment</key>
				<string></string>
				<key>Enabled</key>
				<true/>
				<key>ExecutablePath</key>
				<string></string>
				<key>MaxKernel</key>
				<string></string>
				<key>MinKernel</key>
				<string></string>
				<key>PlistPath</key>
				<string>Contents/Info.plist</string>
			</dict>
```

So it's not the issue per se, but if anyone with this wifi card will struggle getting WiFi to work - this fixes the problem.

**Comment by VinylNerd** [comment]
Thanks

however 2 things i wanna say here

1. use this link for AirportBrcmFixup.kext https://github.com/acidanthera/AirportBrcmFixup

2. there is absolutely no reason to use this card over a BCM94360CS or BCM94360CS2, or BCM943602CS (dont use this card as it doesnt support bluetooth over UEFI

i will include the notes to use this kext for this card on the main readme when i get a chance
